repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
      - id: black-jupyter
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
  - repo: https://github.com/econchick/interrogate/
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [ "-v", "src/" ]
        pass_filenames: false
  - repo: https://github.com/iterative/dvc
    rev: 3.17.0
    hooks:
      - id: dvc-pre-commit
        language_version: python3
        stages:
          - commit
      - id: dvc-pre-push
        additional_dependencies: [ '.[gs]' ]
        language_version: python3
        stages:
          - push
      - always_run: true
        id: dvc-post-checkout
        language_version: python3
        stages:
          - post-checkout
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        stages: [ commit ]
        language: system
        entry: pytest -s -v src/
        types: [ python ]
        pass_filenames: false
        always_run: true
      - id: pytest-cov
        name: pytest-cov
        stages: [ push ]
        language: system
        entry: pytest -v --cov-fail-under=0 --cov-report=term-missing src/
        types: [ python ]
        pass_filenames: false
        always_run: true
