stages:
  train:
    cmd: >
      python
      src/step_counter/models/random/train.py
      data/steps/train/
      models/random.joblib
      reports/metrics/train.json
      --seed=${seed}
    deps:
      - data/steps/train/
    outs:
      - models/random.joblib
    metrics:
      - reports/metrics/train.json
    params:
      - seed
  predict_test:
    cmd: >
      python
      src/step_counter/models/random/predict.py
      data/steps/test/
      models/random.joblib
      reports/predictions/steps/test/
    deps:
      - data/steps/test/
      - models/random.joblib
    outs:
      - reports/predictions/steps/test/
  evaluate:
    cmd: >
      python
      src/step_counter/evaluate.py
      data/steps/test/
      reports/predictions/steps/test/
      reports/figures/
      reports/metrics/
    plots:
      - reports/figures/confusion_matrix.png
      - reports/figures/confusion_matrix_normalized.png
      - reports/figures/roc_curve.png
      - reports/figures/precision_recall_curve.png
    metrics:
      - reports/metrics/test.json
    deps:
      - data/steps/test/
  update-metrics:
    cmd: python update-metrics-table-and-graph.py
    deps:
      - update-metrics-table-and-graph.py
      - reports
