stages:
  train:
    cmd: >
      python
      src/step_counter/train/logistic_regression.py
      data/steps/train/
      models/logistic_regression.joblib
      --seed=${seed}
    deps:
      - data/steps/train/
    outs:
      - models/logistic_regression.joblib
    params:
      - seed
#  evaluate:
#    cmd: >
#      python
#      src/step_counter/evaluate.py
#      data/steps/test/
#      models/logistic_regression.joblib
#    deps:
#      - data/steps/test/
#      - models/logistic_regression.joblib
