stages:
  train:
    cmd: >
      python
      src/step_counter/models/random/train.py
      data/steps/train/
      models/random.joblib
      reports/metrics/train.json
      --seed=${seed}
    deps:
      - data/steps/train/
    outs:
      - models/random.joblib
    metrics:
      - reports/metrics/train.json
    params:
      - seed
  predict_test:
    cmd: >
      python
      src/step_counter/models/random/predict.py
      data/steps/test/
      models/random.joblib
      reports/predictions/steps/test/
    deps:
      - data/steps/test/
      - models/random.joblib
    outs:
      - reports/predictions/steps/test/
  evaluate:
    cmd: >
      python
      src/step_counter/evaluate.py
      data/steps/test/
      reports/predictions/steps/test/
      reports/figures/
      reports/metrics/
    plots:
      - reports/figures/confusion_matrix.csv:
          title: Confusion Matrix (Normalized)
          template: confusion_normalized
          x: actual
          y: predicted
      - reports/figures/precision_recall_curve.csv:
          title: Precision-Recall Curve
          x: recall
          y: precision
      - reports/figures/roc_curve.csv:
          title: ROC Curve
          x: fpr
          y: tpr
    metrics:
      - reports/metrics/test.json
    deps:
      - data/steps/test/
  update-metrics:
    cmd: python update-metrics-table-and-graph.py
    deps:
      - update-metrics-table-and-graph.py
      - reports
plots:
    - reports/figures/confusion_matrix.csv:
        title: Confusion Matrix (Absolute)
        template: confusion
        x: actual
        y: predicted
