stages:
  train:
    cmd: python train.py
    deps:
      - data/train/
    outs:
      - models/model.pkl
  evaluate:
    cmd: python evaluate.py
    deps:
      - models/model.pkl
      - data/test/
