version: 3

tasks:
  list-boards:
    cmds:
      - arduino-cli board list
  arduino-lib-install:
    cmds:
      - arduino-cli core install arduino:mbed_nano
      - arduino-cli lib install Arduino_LSM9DS1
      - arduino-cli lib install ArduinoBLE
      - arduino-cli lib install Arduino_APDS9960
  arduino-accelerometer-compile:
    cmds:
      - arduino-cli --fqbn arduino:mbed_nano:nano33ble compile -e ./arduino/Accelerometer
    sources:
      - ./arduino/Accelerometer/Accelerometer.ino
    generates:
      - ./arduino/Accelerometer/build/**/Accelerometer.ino.*
  arduino-accelerometer-upload:
    deps:
      - arduino-accelerometer-compile
    cmds:
      - arduino-cli upload -p /dev/cu.usbmodem141101 --fqbn arduino:mbed_nano:nano33ble ./arduino/Accelerometer
  arduino-buttons-compile:
    cmds:
      - arduino-cli --fqbn arduino:mbed_nano:nano33ble compile -e ./arduino/Buttons
    sources:
      - ./arduino/Buttons/Buttons.ino
    generates:
      - ./arduino/Buttons/build/**/Buttons.ino.*
  arduino-buttons-upload:
    deps:
      - arduino-buttons-compile
    cmds:
      - arduino-cli upload -p /dev/cu.usbmodem141101 --fqbn arduino:mbed_nano:nano33ble ./arduino/Buttons
  start-live-plotting:
    cmds:
      - bokeh serve --show connect-and-plot.py
  compile-requirements:
    desc: Compile requirements.in to requirements.txt
    sources:
        - pyproject.toml
        - requirements.in
    cmds:
      - pip-compile -o requirements.txt pyproject.toml
  install-requirements:
    desc: Install or update python packages using requirements.txt
    deps:
      - compile-requirements
    sources:
      - requirements.txt
    cmds:
      - pip install -U -r requirements.txt
  test:
    desc: Run tests
    cmds:
      - pytest -v --cov=src --cov-report=term-missing --cov-fail-under=75 src/
