version: 3

tasks:
  list-boards:
    cmds:
      - arduino-cli board list
  arduino-lib-install:
    cmds:
      - arduino-cli core install arduino:mbed_nano
      - arduino-cli lib install Arduino_LSM9DS1
      - arduino-cli lib install ArduinoBLE
      - arduino-cli lib install Arduino_APDS9960
      - arduino-cli lib install Arduino_TensorFlowLite
  arduino-accelerometer-compile:
    cmds:
      - arduino-cli --fqbn arduino:mbed_nano:nano33ble compile -e ./arduino/Accelerometer --log
    sources:
      - ./arduino/Accelerometer/Accelerometer.ino
      - ./arduino/Accelerometer/Model.h
    generates:
      - ./arduino/Accelerometer/build/**/Accelerometer.ino.*
  arduino-accelerometer-upload:
    deps:
      - arduino-accelerometer-compile
    sources:
      - arduino/Accelerometer/build/**/Accelerometer.ino.*
    cmds:
      - |
         board=$(arduino-cli board list -b arduino:mbed_nano:nano33ble | sed -n 's/.*\(\/dev\/[^ ]*\).*/\1/p')
         arduino-cli upload -p $board --fqbn arduino:mbed_nano:nano33ble ./arduino/Accelerometer
  arduino-buttons-compile:
    cmds:
      - arduino-cli --fqbn arduino:mbed_nano:nano33ble compile -e ./arduino/Buttons
    sources:
      - ./arduino/Buttons/Buttons.ino
    generates:
      - ./arduino/Buttons/build/**/Buttons.ino.*
  arduino-buttons-upload:
    deps:
      - arduino-buttons-compile
    cmds:
      - |
         board=$(arduino-cli board list -b arduino:mbed_nano:nano33ble | sed -n 's/.*\(\/dev\/[^ ]*\).*/\1/p')
         arduino-cli upload -p $board --fqbn arduino:mbed_nano:nano33ble ./arduino/Buttons
  start-live-plotting:
    cmds:
      - bokeh serve --show scripts/connect_and_plot.py
  compile-requirements:
    desc: Compile requirements.in to requirements.txt
    sources:
        - pyproject.toml
        - requirements.in
    cmds:
      - pip-compile -o requirements.txt pyproject.toml
  install-requirements:
    desc: Install or update_plot python packages using requirements.txt
    deps:
      - compile-requirements
    sources:
      - requirements.txt
    cmds:
      - pip install -U -r requirements.txt
  test:
    desc: Run tests
    cmds:
      - pytest -v --cov-report html:cov_html --cov=src/step_counter --cov-report=term-missing --cov-fail-under=75 --lf --ff src/
